### ISSUE TITLE
Rate limit file operations

### ISSUE THREAD

**Issue by mfraezz** [dschreij/opensesame-extension-osf#18] opened 2019-04-28 19:15 UTC
This extension is effectively DoS'ing the OSF when users sync large projects. Please consider adding rate limiting.

I believe the offending code is [this loop](https://github.com/dschreij/opensesame-extension-osf/blob/master/opensesame_extensions/OpenScienceFramework/OpenScienceFramework.py#L1515-L1572).

The other obvious option would be to implement it in the [connection manager](https://github.com/dschreij/QOpenScienceFramework/blob/master/QOpenScienceFramework/manager.py#L36).

**Comment by dschreij** [comment] 2019-04-29 07:30
That's not good to hear, and definitely not our intention. It has been our plan to give this extension a big rehaul for a while now, since its performance has been reported to drop with many and/or large projects. The extension currently composes a complete tree of all projects and the repositories with files/folders that they contain at startup. We want to begin by making composition of this tree incremental and 'on demand'.

But for the short term, implementing a rate limiting mechanism seems to be the most sensible option, and the connection manager is indeed the place to do so. I will see what I can do shortly.

**Comment by dschreij** [comment] 2019-05-03 06:06
Just a heads-up. I'm working on this now, and should push a solution within days. I'm only not sure if the code segment you indicated is the culprit, as there is no heavy looping occurring there. How did you get to that section as being the possible suspect of DoS'ing the OSF?

**Comment by mfraezz** [comment] 2019-05-03 14:29
My initial link was referencing `master` rather than a specific commit, so it's outdated by your recent change; [this loop](https://github.com/dschreij/opensesame-extension-osf/blob/a15b0573b76c29e27003c1414bbfd10a091b4d32/opensesame_extensions/OpenScienceFramework/OpenScienceFramework.py#L1576-L1633) is what I meant to reference. 

It's also possible that I'm incorrect about where it's occurring, I spent about 15 minutes poking through the code and that was the first thing that looked suspect to me -- I'm by no means "familiar" with this extension.

**Comment by dschreij** [comment] 2019-05-08 16:28
I think the offender was the [QOpenScienceFramework library](https://github.com/dschreij/QOpenScienceFramework), and we made it treat the OSF API a lot friendlier with the latest commits. We hope to release a newer version soon, but we don't know how fast it will be adopted. Even though we are quite sure that we tackled most of the causes for the DoS, is there a way to test this for you or us?

**Comment by mfraezz** [comment] 2019-05-08 18:20
We can reach out to users we've noticed this from about upgrading, just @ me whenever it's released.

Regarding testing it, I see the `test-settings.json` is [pointed to our `test` environment](https://github.com/dschreij/QOpenScienceFramework/blob/master/QOpenScienceFramework/test-settings.json#L4). We use that for some third-party service evaluations, so I'd recommend using `staging` instead, if possible (`accounts.staging.osf.io`, `api.staging.osf.io/v2/`, and `staging.osf.io` are the relevant urls). That server's intended to be a punching bag.  We have monitoring set up there too, so feel free to hammer it as hard as you like, and I can let you know if we see any spikes.

A reasonable test case would probably be to create about a thousand small but non-empty text files and try to sync them to a project. This will put 1000 random 10kb files in your current working directory:
```
seq -w 1 1000 | xargs -n1 -I% sh -c 'dd if=/dev/urandom of=%.txt bs=10 count=1024'
```
Replace `1000` if you want more or fewer files, and `of=%.txt` with something like `of=%_$(echo $RANDOM | md5).txt` if you want unique filenames across multiple runs.

It's not exactly what's going wrong on prod, but given resource differences between environments, it should be approximately analogous.

**Comment by dschreij** [comment] 2019-05-09 12:08
Thanks for these instructions. I'll see what I can do with them and stress
test your staging server.
I still find it odd that the file syncing code may be the culprit, as
OpenSesame at most syncs 2 datafiles per experiment, as far as I know, and
an experiment takes a while to complete. I'll still look into it
regardless, and I'm just wondering what I'm currently overlooking.

>

**Comment by mfraezz** [comment] 2019-05-13 18:21
>OpenSesame at most syncs 2 datafiles per experiment

That's... surprising to me. I could have also overlooked something. 

We saw spikes in both throughput and response times for file-upload related callbacks when users (self-reported, after reaching out) synced with this app, and the handful of projects I inspected all had file counts in the hundreds or thousands, most of which had multiple versions; so it seemed a reasonable assumption that this app was syncing many files much too quickly. It could alternatively be a user-specific workflow.

Off-hand, do you know if any older versions of OpenSesame may have synced more than two? Otherwise, this integration may have been a red herring, and I apologize for wasting your time, if so.

**Comment by dschreij** [comment] 2019-05-14 07:53
Hmmm, one possibility is that these concern buffered requests. Whenever the extension does a request to the OSF, this request is buffered in case the token has expired and the user needs to re-login. After the same (!) user has logged in again, the buffered requests are sent again. This could increase the amount of files that are sent concurrently slightly, but would never reach the hundreds of thousands.

@smathot correct me if I'm wrong, or please add some options that I'm forgetting, but OpenSesame usually only sends to the OSF after completion of an experiment:
1. OpenSesame's own datafile
2. Eyetracker datafiles (if applicable).

I'm also wondering: This extension has been used since end 2016. Has this problem only popped up recently?

I could (and should) implement rate limiting to prevent this, but I think we are only fighting symptoms then, and not the cause of the problem. If the extension tries to sync thousands of files at once, something else is going awry and should be fixed.,

**Comment by smathot** [comment] 2019-05-14 08:15
> correct me if I'm wrong, or please add some options that I'm forgetting, but OpenSesame usually only sends to the OSF after completion of an experiment:

Another moment is (or can be, if it's enabled) when the experiment is saved. Then the new version is also synced to the OSF.

I suspect that the actual syncing is not what caused all the requests, but rather the refreshing of the project tree. I have a lot of projects, and this could take very very long to the point that the extension was unusable. And this should be resolved with Daniel's latest fixes.

**Comment by dschreij** [comment] 2019-05-14 08:32
> We saw spikes in both throughput and response times for file-upload related callbacks when users (self-reported, after reaching out) synced with this app.

But those are not file-uploaded related, so that's where it strikes me as weird.

**Comment by dschreij** [comment] 2019-07-22 13:27
I think I finally have an idea of where this error comes from. The QOSF library buffers all attempted network requests, so it can retry them in case a user's token has expired and the user has to login again before the requested action can be completed.

I can now see a scenario in which someone runs many participants for which the data is to be uploaded to the OSF. If the user's token has expired, all these upload requests are buffered to be executed until the user logs in again. If he or she only does this again at the end of the day, then all the buffered requests are executed at once. I haven't verified this scenario, but it seems most likely to me that this is what happens, after I have been working quite extensively with the OSF extension myself for a while.

This procedure (i.e. the buffering structure) was chosen because we use OAuth's implicit grant authentication, for which the token apparently is only valid for an hour or so, and cannot be automatically refreshed without the user explicitly logging in again. The implicit grant was chosen because our OSF extension can be regarded as a public client.

I currently have no idea on how to solve this problem without breaking our buffering mechanism, which is very important to keep intact, so I will have to give it some thought. If you or @smathot have some ideas, i'd of course love to hear them.

**Comment by mfraezz** [comment] 2019-07-22 16:23
>The implicit grant was chosen because our OSF extension can be regarded as a public client.

I can see how that complicates things. The only solution that readily comes to mind would be allowing an alternate authentication mechanism, e.g. https://osf.io/settings/tokens , but this raises security concerns as well (especially if a common use case involves multi-user university machines).

On the other hand, we've recently made a number of performance and scalability improvements on our end, and I haven't seen this cause service degradation in over a month. It may make sense to defer or close this issue.

**Comment by dschreij** [comment] 2019-07-23 11:18
Thanks for the update! I'm glad that this could be solved by scaling up. If the issue persists or pops up again, we can always reopen it.

**Closed by dschreij** 2019-07-23 11:18 UTC
