### ISSUE TITLE
Pending operations not cancelled when opening another experiment

### ISSUE THREAD

**Issue by smathot** [dschreij/opensesame-extension-osf#13] opened 2017-02-15 08:52 UTC
I encountered the following quirk:

- I opened an experiment that was connected to the OSF
- The latest version on the OSF was newer than the latest version on my computer
- For some reason this version-check took some time to complete
- I became impatient and opened the experiment again
- Now I received two message boxes in a row, indicating that my version and the OSF version differed
- Then something crashed

I was with a student, so I didn't have time to properly document what exactly happened, but I think the underlying cause is clear:

- When a new experiment is opened, pending operations by the OSF extension are not cancelled, as they should be.

Do you think my diagnosis is correct?

**Comment by dschreij** [comment] 2017-03-02 14:51
This is of course undesired behavior. I thought I accounted for this situation, but I will have a look at this right away and fix it if necessary. Great job on finding an edge case again ;) .

**Comment by dschreij** [comment] 2017-03-06 16:15
Should be fixed with https://github.com/dschreij/opensesame-extension-osf/commit/00ff7cdaae9ac28bb8408bd6c9345810f26d78e7

**Comment by dschreij** [comment] 2017-03-23 13:07
I assume this is fixed with the last commit, and since it is hard to reproduce I don't think there is an easy way to test this?

**Closed by dschreij** 2017-03-23 13:07 UTC
Labels: bug
